export const gameInitialized = [
  {
    player: 'black',
    pieces: {
      c8_1: 'rook',
      c8_2: 'knight',
      c8_3: 'bishop',
      c8_4: 'queen',
      c8_5: 'king',
      c8_6: 'bishop',
      c8_7: 'knight',
      c8_8: 'rook',

      c6_1: 'pawn',
      c6_2: 'pawn',
      c6_3: 'pawn',
      c6_4: 'pawn',
      c6_5: 'pawn',
      c6_6: 'pawn',
      c6_7: 'pawn',
      c6_8: 'pawn',
    },
  },
  {
    player: 'white',
    pieces: {
      c3_1: 'pawn',
      c3_2: 'pawn',
      c3_3: 'pawn',
      c3_4: 'pawn',
      c3_5: 'pawn',
      c3_6: 'pawn',
      c3_7: 'pawn',
      c3_8: 'pawn',

      c1_1: 'rook',
      c1_2: 'knight',
      c1_3: 'bishop',
      c1_4: 'king',
      c1_5: 'queen',
      c1_6: 'bishop',
      c1_7: 'knight',
      c1_8: 'rook',
    },
  },
];
